/**
 * Generates supabase/seed.sql from the extracted catalogue data.
 * Run: npx tsx prisma/generate-seed-sql.ts
 *
 * Produces idempotent INSERTs (ON CONFLICT DO NOTHING) using natural string ids
 * so the file is self-contained and FK-safe when pasted into the Supabase SQL editor.
 * Table/column identifiers are quoted PascalCase/camelCase to match the Prisma schema.
 */
import { writeFileSync, mkdirSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import {
  PRODUCTS,
  PRODUCT_MODELS,
  PROJS,
  ORDERS,
  FINISHES_STD,
  FINISHES_BASIC,
  FINISHES_ENGOBE,
} from "./data/catalogue";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---- helpers ----
const q = (v: string | null | undefined) =>
  v === null || v === undefined ? "NULL" : `'${String(v).replace(/'/g, "''")}'`;
const n = (v: number | null | undefined) => (v === null || v === undefined ? "NULL" : String(v));
const NOW = "now()";
const slugify = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

type Models = Record<string, { code: string; eur: number; dims: string }[]>;
const MODELS = PRODUCT_MODELS as Models;

// ---- RBAC (mirrors prisma/seed.ts) ----
const PERMISSIONS = [
  "dashboard.read", "pricing.read", "pricing.manage", "products.read", "products.write",
  "inventory.read", "inventory.write", "orders.read", "orders.write", "leads.read",
  "leads.write", "customers.read", "customers.write", "quotes.read", "quotes.write",
  "quotes.approve", "purchase.read", "purchase.write", "settings.manage", "users.manage",
  "audit.read",
];
const ROLES: { key: string; label: string; perms: string[] | "*" }[] = [
  { key: "SUPER_ADMIN", label: "Super Admin", perms: "*" },
  { key: "ADMIN", label: "Admin Console", perms: PERMISSIONS.filter((p) => p !== "users.manage") },
  { key: "SALES_MANAGER", label: "Sales Manager", perms: ["customers.read","customers.write","quotes.read","quotes.write","quotes.approve","leads.read","leads.write","orders.read"] },
  { key: "SALES_EXECUTIVE", label: "Sales Console", perms: ["customers.read","customers.write","quotes.read","quotes.write","leads.read","leads.write"] },
  { key: "INVENTORY_MANAGER", label: "Inventory Manager", perms: ["inventory.read","inventory.write","products.read","dashboard.read"] },
  { key: "CUSTOMER", label: "Customer", perms: [] },
];
const DEMO_USERS = [
  { email: "superadmin@watcon.net", name: "Super Admin", role: "SUPER_ADMIN" },
  { email: "admin@watcon.net", name: "Maison Admin", role: "ADMIN" },
  { email: "sales.manager@watcon.net", name: "Sales Manager", role: "SALES_MANAGER" },
  { email: "sales@watcon.net", name: "Sales Executive", role: "SALES_EXECUTIVE" },
  { email: "inventory@watcon.net", name: "Inventory Manager", role: "INVENTORY_MANAGER" },
];
const DEMO_HASH = "PHASE2_REPLACE_WITH_ARGON2_HASH";

function tierFor(finishes: string[]): string {
  const set = new Set(finishes);
  if (FINISHES_ENGOBE.every((f) => set.has(f))) return "ENGOBE";
  if (FINISHES_STD.every((f) => set.has(f))) return "STD";
  if (FINISHES_BASIC.every((f) => set.has(f))) return "BASIC";
  return "STD";
}

const out: string[] = [];
const w = (s = "") => out.push(s);
const section = (t: string) => w(`\n-- ============================================================\n-- ${t}\n-- ============================================================`);

w("-- Maison Vierkant India — SEED DATA (auto-generated by prisma/generate-seed-sql.ts)");
w("-- Run AFTER schema.sql. Idempotent: safe to re-run. Catalogue values are exact from the prototype.");
w("BEGIN;");

// Permissions
section("Permissions");
for (const p of PERMISSIONS) {
  w(`INSERT INTO "Permission" ("id","key") VALUES (${q(p)}, ${q(p)}) ON CONFLICT ("id") DO NOTHING;`);
}

// Roles + RolePermission
section("Roles & role permissions");
for (const r of ROLES) {
  w(`INSERT INTO "Role" ("id","key","label") VALUES (${q(r.key)}, ${q(r.key)}, ${q(r.label)}) ON CONFLICT ("id") DO NOTHING;`);
  const grant = r.perms === "*" ? PERMISSIONS : r.perms;
  for (const perm of grant) {
    w(`INSERT INTO "RolePermission" ("roleId","permissionId") VALUES (${q(r.key)}, ${q(perm)}) ON CONFLICT DO NOTHING;`);
  }
}

// Users
section("Demo users (password hashing wired in Phase 2)");
for (const u of DEMO_USERS) {
  w(`INSERT INTO "User" ("id","email","name","passwordHash","roleId","isActive","createdAt","updatedAt") VALUES (${q(u.email)}, ${q(u.email)}, ${q(u.name)}, ${q(DEMO_HASH)}, ${q(u.role)}, true, ${NOW}, ${NOW}) ON CONFLICT ("id") DO NOTHING;`);
}

// Finishes
section("Finishes");
const allFinishes = Array.from(
  new Set([...FINISHES_ENGOBE, ...FINISHES_STD, ...FINISHES_BASIC, ...PRODUCTS.flatMap((p: any) => p.finishes)]),
);
const finishId = (name: string) => "fin_" + slugify(name);
for (const f of allFinishes) {
  w(`INSERT INTO "Finish" ("id","name") VALUES (${q(finishId(f))}, ${q(f)}) ON CONFLICT ("id") DO NOTHING;`);
}

// Categories
section("Categories (series groups)");
const categoryKeys = Array.from(new Set(PRODUCTS.map((p: any) => p.series).filter(Boolean)));
const catId = (key: string) => "cat_" + slugify(key);
for (const key of categoryKeys) {
  w(`INSERT INTO "Category" ("id","key","name") VALUES (${q(catId(key))}, ${q(key)}, ${q(key)}) ON CONFLICT ("id") DO NOTHING;`);
}

// Collection
section("Collections");
w(`INSERT INTO "Collection" ("id","slug","name") VALUES ('featured', 'featured', 'Featured Series') ON CONFLICT ("id") DO NOTHING;`);

// Products + images + finishes + variants + inventory + collection membership
section("Products, variants, images, finishes, inventory");
const usedSlugs = new Set<string>();
const uniqueSlug = (base: string) => {
  let s = base || "series";
  let i = 2;
  while (usedSlugs.has(s)) s = `${base}-${i++}`;
  usedSlugs.add(s);
  return s;
};
let variantCount = 0;
PRODUCTS.forEach((p: any, idx: number) => {
  const slug = uniqueSlug(slugify(p.name || p.id));
  w(`INSERT INTO "Product" ("id","code","slug","name","description","dimsSummary","eurPrice","categoryId","status","createdAt","updatedAt") VALUES (${q(p.id)}, ${q(p.id)}, ${q(slug)}, ${q(p.name)}, ${q(p.desc)}, ${q(p.dims)}, ${n(p.eurPrice ?? 0)}, ${p.series ? q(catId(p.series)) : "NULL"}, 'ACTIVE', ${NOW}, ${NOW}) ON CONFLICT ("id") DO NOTHING;`);
  (p.imgs ?? []).forEach((url: string, i: number) => {
    w(`INSERT INTO "ProductImage" ("id","productId","url","type","sort") VALUES (${q(p.id + "_img" + i)}, ${q(p.id)}, ${q(url)}, ${i === 0 ? "'HERO'" : "'GALLERY'"}, ${i}) ON CONFLICT ("id") DO NOTHING;`);
  });
  const tier = tierFor(p.finishes ?? []);
  (p.finishes ?? []).forEach((fname: string) => {
    w(`INSERT INTO "ProductFinish" ("productId","finishId","tier") VALUES (${q(p.id)}, ${q(finishId(fname))}, ${q(tier)}) ON CONFLICT DO NOTHING;`);
  });
  (MODELS[p.id] ?? []).forEach((m) => {
    w(`INSERT INTO "ProductVariant" ("id","productId","code","eurPrice","dims") VALUES (${q(m.code)}, ${q(p.id)}, ${q(m.code)}, ${n(m.eur)}, ${q(m.dims)}) ON CONFLICT ("id") DO NOTHING;`);
    variantCount++;
  });
  w(`INSERT INTO "Inventory" ("id","productId","warehouse","quantity","lowStockThreshold") VALUES (${q("inv_" + p.id)}, ${q(p.id)}, 'MAIN', ${n(p.stock ?? 0)}, 2) ON CONFLICT ("id") DO NOTHING;`);
  if (idx < 8) {
    w(`INSERT INTO "ProductCollection" ("productId","collectionId") VALUES (${q(p.id)}, 'featured') ON CONFLICT DO NOTHING;`);
  }
});

// Projects
section("Projects");
PROJS.forEach((pr: any, i: number) => {
  w(`INSERT INTO "Project" ("id","name","location","summary","imageUrl","sort","createdAt") VALUES (${q("proj_" + i)}, ${q(pr.name)}, ${q(pr.loc)}, ${q(pr.desc)}, ${q(pr.img)}, ${i}, ${NOW}) ON CONFLICT ("id") DO NOTHING;`);
});

// Pricing rule
section("Default pricing rule (exact prototype defaults)");
w(`INSERT INTO "PricingRule" ("id","name","rate","discountPct","transportPct","packingFlat","dutyPct","gstPct","profitPct","dealerMarkupPct","formulaKey","isActive","createdAt") VALUES ('default','Default',93.5,0,18,1500,25,18,25,0,'STANDARD',true,${NOW}) ON CONFLICT ("id") DO NOTHING;`);

// Settings
section("Settings");
const settings: [string, object][] = [
  ["company", { name: "Maison Vierkant India", curatedBy: "Watcon", supplier: "Atelier Vierkant" }],
  ["tax", { gstPct: 18, currency: "INR", baseCurrency: "EUR" }],
  ["shipping", { freeZones: ["delhi","new delhi","ncr","noida","gurgaon","gurugram","faridabad","ghaziabad"], advancePct: 50 }],
];
for (const [key, value] of settings) {
  w(`INSERT INTO "Setting" ("id","key","value") VALUES (${q("set_" + key)}, ${q(key)}, ${q(JSON.stringify(value))}::jsonb) ON CONFLICT ("id") DO NOTHING;`);
}

// Demo customers + orders
section("Demo customers & orders");
const statusMap: Record<string, string> = { pending: "PENDING", confirmed: "CONFIRMED", shipped: "SHIPPED", delivered: "DELIVERED" };
ORDERS.forEach((o: any) => {
  const custId = "cust_" + o.id;
  w(`INSERT INTO "Customer" ("id","name","createdAt") VALUES (${q(custId)}, ${q(o.client)}, ${NOW}) ON CONFLICT ("id") DO NOTHING;`);
  w(`INSERT INTO "Order" ("id","number","customerId","status","subtotalInr","transportInr","gstInr","totalInr","advanceInr","createdAt","updatedAt") VALUES (${q("ord_" + o.id)}, ${q("MVI-" + o.id)}, ${q(custId)}, ${q(statusMap[o.status] ?? "PENDING")}, ${n(o.total)}, 0, 0, ${n(o.total)}, ${n(Math.round(o.total * 0.5))}, ${q(o.date)}, ${NOW}) ON CONFLICT ("id") DO NOTHING;`);
});

w("\nCOMMIT;");
w(`-- Summary: ${PRODUCTS.length} products, ${variantCount} variants, ${allFinishes.length} finishes, ${PROJS.length} projects, ${ORDERS.length} orders.`);

const dir = join(__dirname, "..", "supabase");
mkdirSync(dir, { recursive: true });
writeFileSync(join(dir, "seed.sql"), out.join("\n") + "\n");
console.log(`✓ supabase/seed.sql written — ${PRODUCTS.length} products, ${variantCount} variants, ${out.length} lines.`);
